#!/usr/bin/env bash

buildargs=''
tag=$1

while getopts 'b:' flag; do
  case "${flag}" in
    b) buildargs="--build-arg branch=${OPTARG} " && tag=$3;;
    *) echo "Usage: ./build [-b BRANCH] YOURTAG" && exit 1;;
  esac
done

if [ -z "${tag}" ]
then
  echo "You have to choose a tag for your image!"
  echo "Usage: ./build [-b BRANCH] YOURTAG"
  exit 1
fi

docker build -t jensschulze/disposabledrupal:${tag} ${buildargs}.
