#!/usr/bin/env bash

branch=''
installprofile=''
tag=''

while getopts 'b:i:t:' flag; do
  case "${flag}" in
    b) branch="--build-arg branch=${OPTARG} ";;
    i) installprofile="--build-arg installprofile=${OPTARG} ";;
    t) tag="${OPTARG} ";;
    *) echo "Usage: ./build [-b BRANCH] [-i INSTALLPROFILE] -t YOURTAG" && exit 1;;
  esac
done

if [ -z "${tag}" ]
then
  echo "You have to choose a tag for your image!"
  echo "Usage: ./build [-b BRANCH] [-i INSTALLPROFILE] -t YOURTAG"
  exit 1
fi

docker build --no-cache -t jensschulze/disposabledrupal:${tag} ${branch}${installprofile}.
